export interface FAQ {
  question: string;
  answer: string;
}

export interface KeyBenefit {
  title: string;
  detail: string;
}

export interface Ingredient {
  id: number;
  name: string;
  slug: string;
  image: string;
  description: string;
  benefits: string[]; // short teaser chips used on the card grid
  howItWorks: string;
  keyBenefits: KeyBenefit[];
  bestFor: string[];
  howToUse: string;
  pairsWith: string[];
  avoidWith: string[];
  proTip: string;
  faqs: FAQ[];
}

export const ingredients: Ingredient[] = [
  {
    id: 1,
    name: "Vitamin C",
    slug: "vitamin-c",
    image: "/images/ingredients/vitamin-c.jpg",
    description:
      "A powerful antioxidant that brightens skin and fades pigmentation.",
    benefits: [
      "Brightens skin",
      "Reduces dark spots",
      "Boosts collagen",
      "Protects from free radicals",
    ],
    howItWorks:
      "Vitamin C (most commonly L-ascorbic acid in skincare) is an antioxidant that neutralizes free radicals generated by UV exposure and pollution before they can break down collagen. It also inhibits tyrosinase, an enzyme involved in melanin production, which is why it's so effective at fading dark spots and evening out skin tone over time.",
    keyBenefits: [
      { title: "Brightens & evens tone", detail: "Reduces the appearance of dullness and hyperpigmentation with consistent use." },
      { title: "Antioxidant protection", detail: "Helps defend skin against environmental stressors like UV and pollution." },
      { title: "Supports collagen production", detail: "Encourages a firmer, more resilient skin texture over time." },
      { title: "Enhances SPF performance", detail: "Layers well under sunscreen to boost your daily UV defense." },
    ],
    bestFor: ["Dull skin", "Hyperpigmentation", "Uneven tone", "Early signs of aging"],
    howToUse:
      "Apply a few drops in the morning after cleansing, before moisturizer and SPF. Start 2–3 times a week if you're new to it, and build up to daily use as your skin adjusts.",
    pairsWith: ["Vitamin E", "Ferulic Acid", "SPF"],
    avoidWith: ["Retinol (use one AM, one PM)", "Direct combination with strong acids"],
    proTip:
      "Vitamin C oxidizes when exposed to air and light — if your serum turns dark yellow or brown, it's lost potency. Store it in a cool, dark place and replace it every 3 months.",
    faqs: [
      {
        question: "Can I use Vitamin C every day?",
        answer:
          "Yes, once your skin has adjusted. Most people tolerate daily morning use well, though sensitive skin may prefer every other day.",
      },
      {
        question: "Can I use Vitamin C and Retinol together?",
        answer:
          "It's best to separate them — Vitamin C in the morning, Retinol at night — since combining them can increase irritation for some skin types.",
      },
    ],
  },
  {
    id: 2,
    name: "Niacinamide",
    slug: "niacinamide",
    image: "/images/ingredients/niacinamide.jpg",
    description:
      "Helps control oil production and strengthens the skin barrier.",
    benefits: [
      "Controls oil",
      "Minimizes pores",
      "Reduces redness",
      "Strengthens skin barrier",
    ],
    howItWorks:
      "Niacinamide (Vitamin B3) supports the skin's natural barrier by boosting ceramide production, which helps skin retain moisture and resist irritants. It also regulates sebum production and calms inflammation, making it one of the most versatile, well-tolerated actives in skincare.",
    keyBenefits: [
      { title: "Balances oil production", detail: "Helps reduce excess shine without over-drying skin." },
      { title: "Minimizes the look of pores", detail: "Refines texture with consistent use over several weeks." },
      { title: "Calms redness & irritation", detail: "Soothes reactive or sensitized skin." },
      { title: "Strengthens the skin barrier", detail: "Improves resilience against environmental stress and moisture loss." },
    ],
    bestFor: ["Oily skin", "Combination skin", "Enlarged pores", "Sensitive or redness-prone skin"],
    howToUse:
      "Apply morning and/or night after cleansing, before heavier creams. It layers well with almost everything, making it a good foundation step in any routine.",
    pairsWith: ["Hyaluronic Acid", "Retinol", "Vitamin C (modern formulations)"],
    avoidWith: ["Pure Vitamin C (older, less stable formulations) — space them out if irritation occurs"],
    proTip:
      "Niacinamide works gradually — most people see visible pore and texture improvements after 4–8 weeks of consistent use, not overnight.",
    faqs: [
      {
        question: "Does Niacinamide actually shrink pores?",
        answer:
          "It doesn't physically shrink pores, but it regulates oil and reduces buildup around them, which makes pores appear smaller and less noticeable.",
      },
      {
        question: "Is Niacinamide good for sensitive skin?",
        answer:
          "Yes — it's one of the gentlest actives available and is often recommended specifically for sensitive or barrier-compromised skin.",
      },
    ],
  },
  {
    id: 3,
    name: "Retinol",
    slug: "retinol",
    image: "/images/ingredients/retinol.jpg",
    description:
      "Improves skin texture and reduces fine lines and wrinkles.",
    benefits: [
      "Smooths wrinkles",
      "Improves texture",
      "Treats acne",
      "Boosts collagen",
    ],
    howItWorks:
      "Retinol is a Vitamin A derivative that speeds up skin cell turnover and stimulates collagen production. This helps fade fine lines, smooth texture, and clear congested pores over time — but it also means skin is more sensitive to sun and can purge or flake as it adjusts.",
    keyBenefits: [
      { title: "Smooths fine lines & wrinkles", detail: "Encourages collagen renewal for firmer-looking skin." },
      { title: "Refines texture", detail: "Speeds up cell turnover for a smoother surface over time." },
      { title: "Helps manage acne", detail: "Keeps pores clearer by preventing dead skin buildup." },
      { title: "Evens skin tone", detail: "Fades post-acne marks and improves overall clarity with consistent use." },
    ],
    bestFor: ["Fine lines & aging concerns", "Uneven texture", "Acne-prone skin", "Enlarged pores"],
    howToUse:
      "Use at night only, starting 1–2 times a week on completely dry skin, gradually building up to nightly use as tolerance improves. Always follow with SPF the next morning — no exceptions.",
    pairsWith: ["Hyaluronic Acid (for hydration buffer)", "Niacinamide"],
    avoidWith: ["Vitamin C (same routine)", "Exfoliating acids (AHA/BHA) on the same night", "Benzoyl peroxide"],
    proTip:
      "The 'sandwich method' — moisturizer, then retinol, then moisturizer again — can reduce irritation for beginners without diluting results.",
    faqs: [
      {
        question: "Why is my skin purging after starting Retinol?",
        answer:
          "Increased cell turnover can temporarily bring underlying congestion to the surface faster. This typically settles within 2–6 weeks as skin adjusts.",
      },
      {
        question: "Can I use Retinol if I'm pregnant?",
        answer:
          "Retinoids are generally advised against during pregnancy and breastfeeding — check with a dermatologist or doctor for a suitable alternative.",
      },
    ],
  },
  {
    id: 4,
    name: "Hyaluronic Acid",
    slug: "hyaluronic-acid",
    image: "/images/ingredients/hyaluronic-acid.jpg",
    description:
      "Provides intense hydration for healthy, plump skin.",
    benefits: [
      "Deep hydration",
      "Plumps skin",
      "Supports skin barrier",
      "Suitable for all skin types",
    ],
    howItWorks:
      "Hyaluronic Acid is a humectant naturally found in skin that can hold up to 1,000 times its weight in water. Applied topically, it draws moisture into the skin's surface, plumping fine lines and improving overall hydration without adding oil.",
    keyBenefits: [
      { title: "Deep, lightweight hydration", detail: "Draws and holds moisture without feeling heavy or greasy." },
      { title: "Plumps fine lines", detail: "Temporarily smooths the look of dehydration lines." },
      { title: "Supports the skin barrier", detail: "Well-hydrated skin is better equipped to resist irritation." },
      { title: "Works for every skin type", detail: "Gentle enough for sensitive, oily, dry, or combination skin." },
    ],
    bestFor: ["Dehydrated skin", "Dry skin", "All skin types as a base hydrator", "Post-active recovery"],
    howToUse:
      "Apply to damp skin morning and night, then seal it in with a moisturizer within a minute or two — applying to dry skin in a dry climate can actually pull moisture out rather than in.",
    pairsWith: ["Niacinamide", "Vitamin C", "Retinol"],
    avoidWith: ["Nothing notable — it's one of the most universally compatible ingredients"],
    proTip:
      "Always apply Hyaluronic Acid to slightly damp skin and lock it in with a moisturizer — using it on bone-dry skin in low humidity can backfire.",
    faqs: [
      {
        question: "Can Hyaluronic Acid cause breakouts?",
        answer:
          "It's non-comedogenic and generally safe for acne-prone skin, since it hydrates without adding oil.",
      },
      {
        question: "Do I still need moisturizer if I use Hyaluronic Acid?",
        answer:
          "Yes — Hyaluronic Acid draws in moisture but doesn't seal it. A moisturizer on top locks that hydration in.",
      },
    ],
  },
];